# Generated by Django 4.1.7 on 2023-04-05 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=20)),
                ("movie_name", models.CharField(max_length=100)),
                ("movie_summary", models.TextField(max_length=5000)),
                ("reg_date", models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(
                    default="익명의 관객", max_length=20)),
                ("review_text", models.TextField(max_length=5000)),
                ("score", models.IntegerField(default=0)),
                ("reg_date", models.DateTimeField(
                    default=django.utils.timezone.now)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.movie"
                    ),
                ),
            ],
        ),
    ]
