# Generated by Django 4.1.7 on 2023-03-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="title1",
            new_name="title",
        ),
    ]
