# Generated by Django 4.1.7 on 2023-03-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_rename_title1_board_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="title",
            new_name="title1",
        ),
    ]
